# Generated by Django 5.2.7 on 2026-01-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0003_alter_certificat_id_alter_course_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('posted_as', models.CharField(choices=[('News', 'News'), ('Event', 'Event')], default='News', max_length=10)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
