# Generated by Django 5.2.7 on 2026-01-07 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0004_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificat',
            options={'ordering': ['id'], 'verbose_name': 'Certificat', 'verbose_name_plural': 'Certificats'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id'], 'verbose_name': 'Leçon', 'verbose_name_plural': 'Leçons'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_as',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='course',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.TextField(default='', verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='post',
            name='titre',
            field=models.CharField(default='', max_length=200, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('Nouveauté', 'Nouveauté'), ('Événement', 'Événement')], default='Nouveauté', max_length=10, verbose_name='Type de post'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursus.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='date_obtention',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'obtention"),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instructeur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Deb', 'Débutant'), ('Int', 'Intermédiaire'), ('Avc', 'Avancé')], default='Deb', max_length=3, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='course',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='cursus.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cursus.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='cursus.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_rendu',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de rendu'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='projets/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
