# Generated by Django 5.2.7 on 2026-01-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0006_course_code_course_credit_course_slug_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Titre du programme')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Résumé')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10, verbose_name='Semestre')),
                ('is_current_semester', models.BooleanField(default=False, verbose_name='Semestre actuel')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, unique=True, verbose_name='Session')),
                ('is_current_session', models.BooleanField(default=False, verbose_name='Session actuelle')),
                ('next_session_beginning', models.DateField(blank=True, null=True, verbose_name='Début de la prochaine session')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Résumé court'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursus.program', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursus.semester', verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursus.session', verbose_name='Session'),
        ),
    ]
