# Generated by Django 5.2.7 on 2026-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0007_program_semester_session_course_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False, verbose_name='Optionnel'),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('1', '1ère Année'), ('2', '2ème Année'), ('3', '3ème Année'), ('4', '4ème Année')], default='1', max_length=1, verbose_name='Année'),
        ),
    ]
