# Generated by Django 5.2.7 on 2026-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0008_course_is_elective_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Image'),
        ),
    ]
