# Generated by Django 5.2.7 on 2026-01-12 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0010_question_alter_certificat_id_alter_course_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cursus.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Devoir/Projet',
                'verbose_name_plural': 'Devoirs/Projets',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Score obtenu')),
                ('date_attempted', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cursus.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/', verbose_name='Fichier rendu')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire étudiant')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('grade', models.FloatField(blank=True, null=True, verbose_name='Note')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback instructeur')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cursus.assignment', verbose_name='Devoir')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Rendu',
                'verbose_name_plural': 'Rendus',
            },
        ),
    ]
