# Generated by Django 5.2.7 on 2026-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_profile_id_alter_score_id_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['id'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('ETU', 'Étudiant'), ('INS', 'Instructeur')], default='ETU', max_length=3, verbose_name="Type d'utilisateur"),
        ),
    ]
