# Generated by Django 5.2.7 on 2026-01-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursus', '0007_program_semester_session_course_summary_and_more'),
        ('utilisateur', '0003_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='level',
            field=models.CharField(choices=[('100', 'Niveau 100'), ('200', 'Niveau 200'), ('300', 'Niveau 300'), ('400', 'Niveau 400')], default='100', max_length=3, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursus.program', verbose_name='Programme'),
        ),
    ]
